sudo: required
services:
  - docker

install:
    docker build . -t lib-mapknitter-exporter:latest

script:
    docker run lib-mapknitter-exporter ruby test/exporter_test.rb

branches:
   only:
    - main
    - unstable
